
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 5;
  public static final int CAMPO = 4;
  public static final int error = 1;
  public static final int PUNTO_COMA = 6;
  public static final int FROM = 2;
  public static final int EOF = 0;
  public static final int SELECT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FROM",
  "SELECT",
  "CAMPO",
  "COMA",
  "PUNTO_COMA"
  };
}

